# Generated by Django 5.2.9 on 2025-12-22 09:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_certificate_yn'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAIReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_summary', models.CharField(blank=True, help_text='LLM이 생성한 강좌 요약 (2-3문장 제한)', max_length=1000)),
                ('average_rating', models.FloatField(help_text='종합 평점 (0.0-5.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('theory_rating', models.FloatField(help_text='이론적 깊이 (0: 얕음, 5: 깊음)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('practical_rating', models.FloatField(help_text='실무적 활용도 (0: 낮음, 5: 높음)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('difficulty_rating', models.FloatField(help_text='학습 난이도 (0: 쉬움, 5: 어려움)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('duration_rating', models.FloatField(help_text='학습 기간 (0: 짧음, 5: 김)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('model_version', models.CharField(default='gpt-4o-mini', help_text='사용된 LLM 모델 버전', max_length=50)),
                ('prompt_version', models.CharField(default='v1.0.0', help_text='사용된 프롬프트 템플릿 버전', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(help_text='평가 대상 강좌', on_delete=django.db.models.deletion.CASCADE, related_name='ai_review', to='courses.course')),
            ],
            options={
                'verbose_name': '강좌 AI 평가',
                'verbose_name_plural': '강좌 AI 평가 목록',
                'db_table': 'course_ai_review',
                'indexes': [models.Index(fields=['average_rating'], name='course_ai_r_average_569a56_idx'), models.Index(fields=['theory_rating'], name='course_ai_r_theory__b1088d_idx'), models.Index(fields=['practical_rating'], name='course_ai_r_practic_15c5a7_idx')],
            },
        ),
    ]
