# Generated by Django 5.2.9 on 2025-12-22 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseaireview',
            name='average_rating',
            field=models.FloatField(help_text='종합 평점 (1.0-5.0)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='courseaireview',
            name='difficulty_rating',
            field=models.IntegerField(help_text='학습 난이도 (1: 입문자용, 5: 고급)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='courseaireview',
            name='duration_rating',
            field=models.IntegerField(help_text='학습 기간 (1: 1-4주, 5: 17주 이상)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='courseaireview',
            name='practical_rating',
            field=models.IntegerField(help_text='실무적 활용도 (1: 이론 중심, 5: 프로젝트 중심)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='courseaireview',
            name='theory_rating',
            field=models.IntegerField(help_text='이론적 깊이 (1: 매우 기초적, 5: 고급)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
