# Generated by Django 5.2.9 on 2025-12-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_yn',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
