# Generated by Django 5.2.4 on 2025-12-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_certificate_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='raw_summary',
            field=models.TextField(blank=True, null=True, verbose_name='강좌 소개(HTML 원본)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='강좌 썸네일'),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='강좌 요약/소개'),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='강좌 URL'),
        ),
    ]
