# Generated by Django 5.2.9 on 2025-12-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_raw_summary_alter_course_course_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='raw_summary',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
